function  extra_check_different_loop( phi3,phi4,phi5,phi6,phi7,phi8,phi9,phi10, ...
           dphi3,dphi4,dphi5,dphi6,dphi7,dphi8,dphi9,dphi10, ...
           ddphi3,ddphi4,ddphi5,ddphi6,ddphi7,ddphi8,ddphi9,ddphi10, ...
           Ts, fig_kin_check_different_loop, t)
       
       
       
       
        figure

        subplot(331)
            plot(t(1:size(erddphi3),:),ddiffphi3)
            ylabel('dd\phi_3 approximation [rad]')
            xlabel('t [s]')
        subplot(332)
            plot(t,ddphi3)
            ylabel('dd\phi_3 exact [rad]')
            xlabel('t [s]')
        subplot(333)
            plot(t(1:size(erddphi3),:),erddphi3)
            ylabel('error [rad]')
            xlabel('t [s]')
        subplot(334)
            plot(t(1:size(erddphi4),:),ddiffphi4)
            ylabel('dd\phi_4 approximation [rad]')
            xlabel('t [s]')
        subplot(335)
            plot(t,ddphi4)
            ylabel('dd\phi_4 exact [rad]')
            xlabel('t [s]')
        subplot(336)
            plot(t(1:size(erddphi4),:),erddphi4)
            ylabel('error [rad]')
            xlabel('t [s]')
        subplot(337)
            plot(t(1:size(erddphi5),:),ddiffphi5)
            ylabel('dd\phi_5 approximation [rad]')
            xlabel('t [s]')
        subplot(338)
            plot(t,ddphi5)
            ylabel('dd\phi_5 exact [rad]')
            xlabel('t [s]')
        subplot(339)
            plot(t(1:size(erddphi5),:),erddphi5)
            ylabel('error [rad]')
            xlabel('t [s]')

        figure

        subplot(331)
            plot(t(1:size(erddphi6),:),ddiffphi6)
            ylabel('dd\phi_6 approximation [rad]')
            xlabel('t [s]')
        subplot(332)
            plot(t,ddphi6)
            ylabel('dd\phi_6 exact [rad]')
            xlabel('t [s]')
        subplot(333)
            plot(t(1:size(erddphi6),:),erddphi6)
            ylabel('error [rad]')
            xlabel('t [s]')
        subplot(334)
            plot(t(1:size(erddphi7),:),ddiffphi7)
            ylabel('dd\phi_7 approximation [rad]')
            xlabel('t [s]')
        subplot(335)
            plot(t,ddphi7)
            ylabel('dd\phi_7 exact [rad]')
            xlabel('t [s]')
        subplot(336)
            plot(t(1:size(erddphi7),:),erddphi7)
            ylabel('error [rad]')
            xlabel('t [s]')
        subplot(337)
            plot(t(1:size(erddphi8),:),ddiffphi8)
            ylabel('dd\phi_8 approximation [rad]')
            xlabel('t [s]')
        subplot(338)
            plot(t,ddphi8)
            ylabel('dd\phi_8 exact [rad]')
            xlabel('t [s]')
        subplot(339)
            plot(t(1:size(erddphi8),:),erddphi8)
            ylabel('error [rad]')
            xlabel('t [s]')

        figure
        subplot(331)
            plot(t(1:size(erddphi9),:),ddiffphi9)
            ylabel('dd\phi_9 approximation [rad]')
            xlabel('t [s]')
        subplot(332)
            plot(t,ddphi9)
            ylabel('dd\phi_9 exact [rad]')
            xlabel('t [s]')
        subplot(333)
            plot(t(1:size(erddphi9),:),erddphi9)
            ylabel('error [rad]')
            xlabel('t [s]')
        subplot(334)
            plot(t(1:size(erddphi10),:),ddiffphi10)
            ylabel('dd\phi_{10} approximation [rad]')
            xlabel('t [s]')
        subplot(335)
            plot(t,ddphi10)
            ylabel('dd\phi_{10} exact [rad]')
            xlabel('t [s]')
        subplot(336)
            plot(t(1:size(erddphi10),:),erddphi10)
            ylabel('error [rad]')
            xlabel('t [s]')

end
